name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 1
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-test-dev
      - name: 2
        run: cmake -H. -B_build -DBUILD_TESTS=ON
      - name: 3
        run: cmake --build _build
      - name: 4
        run: cmake --build _build --target test -- ARGS=--verbose
      - name: 5
        run: cmake --build _build --target install/a\- cmake --build _build --target test -- ARGS=--verbose
      - name: last
        run: |
          mkdir artifacts
          sleep 20s && gnome-screenshot --file artifacts/screenshot.png
