
name: CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 1
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-test-dev
      - name: 2
        run: cmake -H. -B_build -DCOVERAGE=ON
      - name: 3
        run: cmake --build _build
      - name: 4
        run: |
          cmake --build _build --target test_acc
          cd _build
          ./test_acc
          cd -
      - name: lcov
        run: sudo apt-get install -y lcov
      - name: cover
        run: |
          lcov -c -d _build/  -o ./lcov_tmp.info
          lcov -r ./lcov_tmp.info '*googletest*'  '*usr*' -o ./lcov.info
          genhtml lcov.info --output-directory out
      - name: save coverage
        uses: coverallsapp/github-action@master
        with:
            path-to-lcov: "./lcov.info"
            github-token: ${{ secrets.github_token }}
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
            name: coverage-report
            path: out/
