name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-test-dev
      - name: Configure CMake
        run: cmake -H. -B_build -DBUILD_TESTS=ON=ON
      - name: Build
        run: |
          cmake --build _build
          cmake --build _build --target tests -- ARGS=--verbose
      - name: Run tests
        run: |
          cd _build
          ./check
          cd ..
      - name: Install lcov
        run: sudo apt-get install -y lcov
      - name: Generate coverage report
        run: |
            lcov --capture --directory _build/ -o ./coverage.info
            lcov -r ./coverage.info '*googletest*'  '*usr*' -o ./coverage2.info
      - name: save coverage
        uses: coverallsapp/github-action@master
        with:
            path-to-lcov: "./coverage2.info"
            github-token: ${{ secrets.github_token }}
