name: CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 1
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-test-dev
      - name: 2
        run: cmake -H. -B_build -DBUILD_TESTS=ON
      - name: 3
        run: cmake --build _build
      - name: 4
        run: cmake --build _build --target test -- ARGS=--verbose
      - name: 6
        run: |
          pip install cpp-coveralls
          export COVERALLS_REPO_TOKEN=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
          coveralls --exclude lib --exclude tests --gcov-options '\-lp'
      - name: 7
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}
