name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-test-dev
      - name: Configure CMake
        run: cmake -H. -B_build -DCOVERAGE=ON
      - name: Build
        run: cmake --build _build
      - name: Run tests
        run: |
          cmake --build _build --target test_acc
          cd _build
          ./test_acc
          cd ..
      - name: Install lcov
        run: sudo apt-get install -y lcov
      - name: Generate coverage report
        run: |
          lcov --directory _build --capture --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --remove coverage.info '*/googletest/*' --output-file coverage.info
          lcov --list coverage.info
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.info
      - name: Archive source code
        run: zip -r source.zip .
        if: always()
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: source-code
          path: source.zip
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.info
