name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-test-dev
      - name: Configure CMake
        run: cmake -H. -B_build -DCOVERAGE=ON
      - name: Build
        run: cmake --build _build
      - name: Run tests
        run: |
          cmake --build _build --target test_acc
          cd _build
          ./test_acc
          cd ..
      - name: Install lcov
        run: sudo apt-get install -y lcov
      - name: Generate coverage report
        run: |
          lcov --directory _build --capture --output-file ./coverage.info
          lcov --remove ./coverage.info '/usr/*' --output-file ./coverage.info
          lcov --remove ./coverage.info '*/googletest/*' --output-file ./coverage.info
          lcov --list coverage.info
      - name: save coverage
        uses: coverallsapp/github-action@master
        with:
            path-to-lcov: "./coverage.info"
            github-token: ${{ secrets.github_token }}
